### ISSUE TITLE
Demo link has missing images - 404 

### ISSUE THREAD

**Issue by pepperstreet** [kidGodzilla/jquery.viewport-crop.js#2]
Hello, just noticed the demo has no images. Browser console says "not found - 404".

Demo link:
http://jamesfuthey.com/viewport-crop/

Requested image files:
http://jamesfuthey.com/phantombuilder.com/themes/spirito/assets/img/demo/bg_1.jpg
http://jamesfuthey.com/phantombuilder.com/themes/spirito/assets/img/demo/bg_5.jpg

**Comment by kidGodzilla** [comment]
Thanks!
