### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by neonDog** [kidGodzilla/jquery.viewport-crop.js#3]
A mousewheel zoom would be terrific. Also the zoom would be better if it kept the image centralized (like cropper.js does) instead of growing/shrinking from the top-left corner.

**Comment by kidGodzilla** [comment]
Thanks for the suggestions! If I end up using this library again in the future I'll look into feature requests, but for now I'm just maintaining it and fixing bugs. Feel free to try your hand at a pull request though, if you like.

Thanks!
